name: woolydart
description: A llama.cpp wrapper for Dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

dependencies:
  ffi: ^2.1.2
  format: ^1.5.2

dev_dependencies:
  ffigen: ^12.0.0
  lints: ^4.0.0
  test: ^1.24.0

ffigen:
  name: 'woolydart'
  description: 'llama.cpp binding'
  output: 'lib/src/llama_cpp_bindings.dart'
  llvm-path:
    - '/opt/homebrew/opt/llvm'
  #ignore-source-errors: true
  #exclude-all-by-default: true
  headers:
    entry-points:
      - 'src/llama.cpp/bindings.h'
  compiler-opts:
    - '-Isrc/llama.cpp/'
#    - '-I/usr/lib/clang/17/include'
#    - '-I/opt/homebrew/opt/llvm/include/c++/v1'
