name: woolydart
description: A llama.cpp wrapper for Dart that has a high-level wrapper with low-level functions exposed.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

dependencies:
  ffi: ^2.1.2
  format: ^1.5.2

dev_dependencies:
  args: ^2.5.0
  ffigen: ^12.0.0
  lints: ^4.0.0
  test: ^1.24.0

ffigen:
  name: 'woolydart'
  description: 'llama.cpp binding'
  output: 'lib/src/llama_cpp_bindings.dart'
  llvm-path:
    - '/opt/homebrew/opt/llvm'
  ignore-source-errors: true
  headers:
    entry-points:
      - 'src/bindings.h'
      - 'src/llama.cpp/llama.h'
  compiler-opts:
    - '-Isrc/llama.cpp/'